server:
  port: 8080

application:
  token:
    prefix: "~"
    expiration-days: 1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
